apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ake343ezz-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ake343ezz-dotnet-basic-gitops