apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ake343ezz-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:826e1bd2a5c7ee37305e15e20d4437f6d89f2bbd@sha256:ed95df83b9fca9d1d064fc1028fc09cd5d7e0cbf38564cf6ea7ef29e788c4b6b
          name: container-image
